media:
  input: public/uploads
  output: /uploads

content:
  - name: posts
    label: English
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Pub Date, type: date }
      - { name: modDatetime, label: Mod Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - name: image
        label: Image
        type: image
        options:
          extensions: [jpg, jpeg, png, webp, avif]
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }

  - name: posts_de
    label: Deutsch
    type: collection
    path: src/content/blog/de
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Autor, type: string }
      - { name: pubDatetime, label: Publk. Datum, type: date }
      - { name: modDatetime, label: Geändert am, type: date }
      - { name: title, label: Titel, type: string, required: true }
      - name: image
        label: Bild
        type: image
        options:
          extensions: [jpg, jpeg, png, webp, avif]
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Empfohlen, type: boolean }
      - { name: draft, label: Entwurf, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Inhalt, type: rich-text }
