content:
  - name: posts
    label: English
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - name: image
        label: Image
        type: image
        options:
          path: public/uploads/posts
          extensions: [jpg, jpeg, png, webp, avif]
      - { name: ogImage, label: OG Image, type: image, options: { path: public/uploads/posts, extensions: [jpg, jpeg, png, webp, avif] } }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: posts_de
    label: Deutsch
    type: collection
    path: src/content/blog/de
    view:
      fields: [title, draft, date]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - name: image
        label: Bild
        type: image
        options:
          path: public/uploads/posts/de
          extensions: [jpg, jpeg, png, webp, avif]
      - { name: ogImage, label: OG Bild, type: image, options: { path: public/uploads/posts/de, extensions: [jpg, jpeg, png, webp, avif] } }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Beschreibung, type: string }
      - { name: body, label: Text, type: rich-text }
